### ISSUE TITLE
PROG1 PATH specified in grab script seems to be incorrect

### ISSUE THREAD

**Issue by bbiiggppiigg** [barghouthi/cs704#2]
In the file /u/a/w/aws/public/html/courses/cs704-code/asn1/grab

PROG1 is set to some folder under cs704-s17

`PROG1='/u/a/w/aws/public/html/courses/cs704-s17/code/asn1'`

which doesn't exist 
I think it should be 
`PROG1='/u/a/w/aws/public/html/courses/cs704-code/asn1'`
instead

**Comment by barghouthi** [comment]
Thank you. Fixed.
