### ISSUE TITLE
Ocaml Path Info on CSL machine needs to be updated

### ISSUE THREAD

**Issue by bbiiggppiigg** [barghouthi/cs704#3]
On CSL machines, the original path to ocal libraries
`/unsup/ocaml/bin`
no longer works

Now Ocaml libraries are now available under 
`/unsup/ocaml/amd64_rhel6/bin/`
or 
`/unsup/ocaml/amd64_rhel7/bin/`

**Comment by barghouthi** [comment]
Thank you. Fixed.
