### ISSUE TITLE
rlwrap: Cannot execute ocamlc: No such file or directory

### ISSUE THREAD

**Issue by samlemley** [barghouthi/cs704#4]
I'm having trouble getting "rlwrap ocamlc" to run. Do you notice something I'm doing incorrectly or a step I might be missing?

1. Connect to "best-linux.cs.wisc.edu" using PuTTY

2. Add rlwrap and ocaml to the PATH environment variable
$ PATH=$PATH:/unsup/rlwrap/amd64_rhel6/bin:/unsup/ocaml/amd64_rhel7/bin

3. Attempt to run "rlwrap ocamlc" - at this point I receive the error "rlwrap: Cannot execute ocamlc: No such file or directory."
$ rlwrap ocamlc
rlwrap: Cannot execute ocamlc: No such file or directory

Note that if I enter "ocamlc" at the prompt by itself, I receive the following message:
$ ocamlc
-bash: /unsup/ocaml-4.02.3/amd64_rhel7/bin/ocamlc: /unsup/ocaml-4.02.3/@sys/bin/ocamlrun: bad interpreter: No such file or directory

While if I enter "rlwrap" at the prompt by itself, I receive the following message:
$ rlwrap
Usage: rlwrap [options] command ...
Options:
...
bug reports, suggestions, updates:
http://utopia.knoware.nl/~hlub/uck/rlwrap/
$

Thank you!

**Comment by bbiiggppiigg** [comment]
Guess this is related to the CSL machine changes from red hat-linux to ubuntu
which makes the @sys command reporting amd64_ubu14/amd64_ubu16 instead of amd64_rhel7/amd64_rhe6, resulting in probably all ocamlrun-depending scripts report this not found error.
Saying so, I don't know how to overwrite the outcome of @sys in a bash_script, probably a issue that needs to be reported to the CSL .

If the @sys issue can be fixed, then the changes made in #3 probably should be reverted.

**Comment by samlemley** [comment]
Cool, thanks for taking a look! I've sent an email to lab@cs.wisc.edu to request that CSL staff take a look and I've cc'd Professor Albarghouthi.

**Comment by samlemley** [comment]
A quick update, folks from CSL have installed rlwrap and ocaml on the instructional computers which they expect should address this issue. We should now be able to access both pieces of software without  making any PATH changes.

I'm currently away from a computer I could use to verify that this addresses the issue. I will check back in this evening and let you all know how things go. (If anyone here tries this out before I have a chance to, please let us know :))

**Comment by barghouthi** [comment]
I checked on one of the instructional machines, and ocaml and rlwrap are indeed installed.

**Comment by samlemley** [comment]
Awesome, I just verified this as well. I am able to successfully run rlwrap ocaml and rlwrap ocamlc. Thank you!

**Comment by rhabib1211** [comment]
rlwrap -f . -r nc -nvlp 4444 "this command doesn't work "
SHOW this msg: rlwrap: """error: Could not open /root/.nc_history: No such file or directory"""
