### ISSUE TITLE
Somthing potentially wrong with ToDeBruijinCheck.ml

### ISSUE THREAD

**Issue by bbiiggppiigg** [barghouthi/cs704#5]
In the default ToDeBuijnCheck.ml,
at line 10, it prints out the original lambda expression before printing out the output of function to_debruijn, thus the script will consider the output incorrect.

I bypassed this issue by copying the entire code skeleton folder and comment out line 10, but if this code is a part of the automated tester for grading, then probably this issue needs to be fixed

**Comment by barghouthi** [comment]
The grading/checking script is "./check". It does invoke ToDeBruijnCheck.
You are right: Currently it prints out lambda expression first; I will fix it shortly.

**Comment by barghouthi** [comment]
Fixed by commenting out line 10. 
Thank you!
